train: 
  train_steps: 1000000
  val_freq: 100
  save_freq: 1000
  keep_ckpts: 3
  lr: 1e-4
  logs_folder: 'ttts/diffusion/logs'
  accumulate_num: 1
  unconditioned_percentage: 0.1
  timesteps: 1000
dataset:
  path: /home/hyc/tortoise_plus_zh/ttts/datasets/hq_data.jsonl
  gpt_path: /home/hyc/tortoise_plus_zh/ttts/gpt/logs/2024-03-04-14-56-52/model-200.pt
dataloader:
  batch_size : 64
  shuffle: true
  num_workers : 64
  drop_last: true 
  pin_memory: true

aa_diffusion:
  in_channels: 100
  out_channels: 200
  model_channels: 512
  num_heads: 16
  num_layers: 6
  in_latent_channels: 512
  dropout: 0
  layer_drop: 0.1
  # mrte:
  #   mel_channels : 512
  #   semantic_channels : 512
  #   model_channels : 512
  #   out_channels : 512
  #   num_heads : 8